spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zwl@910425
    url: jdbc:mysql://111.231.196.241:3306/SpringCloudSell?characterEncoding=utf-8&useSSL=false
  #rabbitmq配置
  rabbitmq:
    host: 111.231.196.241
    port: 5672
    username: guest
    password: zwl@910425
  redis:
    host: localhost
    port: 6379
    database: 2
zuul:
  routes:
  # /myProduct/product/list -> /product/product/list
    myProduct:
      myProduct: /myProduct/**
      serviceId: product
  #简洁写法
  #    product: /myProduct/**
  #排除某些路由
  ignored-patterns:
    - /**/product/listForOrder
  #将敏感头不过滤(cookies之类的)
  sensitive-headers:
management:
  security:
    enabled: false
